osx_image: xcode7
language: objective-c
script: xctool -scheme StatefulViewControllerTests -sdk iphonesimulator test
sudo: false
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
